### ISSUE TITLE
Allow .bandit name for the config file

### ISSUE THREAD

**Issue by lachmanfrantisek** [codacy/codacy-bandit#12]
Hi,

would it be possible to use also `.bandit` name for the config file, since it is the default?

Or at least write somewhere a note to be able to get the right name easily, so people do not need to go through the code:
https://github.com/codacy/codacy-bandit/blob/master/src/main/scala/codacy/bandit/Bandit.scala#L68

Thanks in advance!

**Comment by rtfpessoa** [comment]
@lachmanfrantisek thanks for your feedback. Feel free to send a PR with the new filename(s).

Currently we have some docs on the platform https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns#5-existing-tools, but adding that information to the readme could be a good idea.

**Comment by lachmanfrantisek** [comment]
@rtfpessoa thanks so much for the link.

I've never done anything in the Scala, but I will try to add this small change and send PR.
