### ISSUE TITLE
[CY-4330] Rule names include spurious permalink Markdown

### ISSUE THREAD

**Issue by prcr** [codacy/codacy-bandit#46]
The names of the Bandit rules on Codacy include spurious Markdown code from the permalinks in the [original documentation](https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html):

![image](https://user-images.githubusercontent.com/60105800/118158753-1cc5c200-b414-11eb-83a3-74fcd62feec1.png)

**Comment by lolgab** [comment]
Fixed in https://github.com/codacy/codacy-bandit/pull/47
