### ISSUE TITLE
[TS-634] [BUG] `.bandit` file is used as config, should be ini

### ISSUE THREAD

**Issue by jkowalleck** [codacy/codacy-bandit#62]
## observed 

If `.bandit` file is found, it is run with `bandit -c .bandit`.  (see above)
This is wrong.

## expected
`.bandit` file is expected to be in INI format and must be run with `bandit --ini .bandit`.

https://bandit.readthedocs.io/en/latest/config.html#
>  To use this, put an INI file named `.bandit` in your project’s directory. [...]

## contact

https://github.com/codacy/codacy-bandit/blob/ab42badc52e207130748e968387f5246c09b5ca9/src/main/scala/codacy/bandit/Bandit.scala#L35

BTW: the `bandit.yml` is a config, not an INI, and is correctly called with `bandit -c bandit.yml`

**Comment by jkowalleck** [comment]
impact: 
`.bandit` file is in INI format.
if this file is loaded via `-c` instead of `--ini`, then `bandit` crashes, causing your docker image to crash on runtime.

**Comment by jkowalleck** [comment]
possible fix: https://github.com/codacy/codacy-bandit/pull/63

**Comment by DMarinhoCodacy** [comment]
Hello @jkowalleck 
I'm sorry for the time we took to reply.
Thanks for opening a PR. In the next days we're going to check your changes and test accordingly.
Thanks once more,
David
